/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f7f9fe",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f1f4f9",
        "on-secondary-container": "#217128",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef1f6",
        "tertiary-fixed-dim": "#f8bd2a",
        "on-background": "#181c20",
        "inverse-surface": "#2d3135",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#414750",
        "on-secondary-fixed-variant": "#005312",
        "surface-variant": "#dfe3e8",
        "primary": "#003e6f",
        "on-tertiary-fixed": "#261a00",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-primary-fixed": "#001c37",
        "surface": "#f7f9fe",
        "on-surface": "#181c20",
        "surface-dim": "#d7dadf",
        "surface-container-highest": "#dfe3e8",
        "surface-container-high": "#e5e8ed",
        "secondary-fixed-dim": "#88d982",
        "secondary": "#1b6d24",
        "on-secondary-fixed": "#002204",
        "outline-variant": "#c1c7d2",
        "on-primary-container": "#a5cbff",
        "on-secondary": "#ffffff",
        "tertiary": "#4f3900",
        "tertiary-container": "#6c4f00",
        "primary-fixed-dim": "#a1c9ff",
        "surface-tint": "#1961a1",
        "secondary-fixed": "#a3f69c",
        "on-primary-fixed-variant": "#004880",
        "secondary-container": "#a0f399",
        "inverse-primary": "#a1c9ff",
        "tertiary-fixed": "#ffdfa0",
        "background": "#f7f9fe",
        "surface-container": "#ebeef3",
        "primary-container": "#005696",
        "primary-fixed": "#d2e4ff",
        "on-tertiary-container": "#fabf2c",
        "surface-container-lowest": "#ffffff",
        "outline": "#727781"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
